---
title: "DDHW on a simple simulation"
author: "N. Ignatiadis"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Introduction to ddhw"}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r}
library("ddhw")
```

Use a simple simulation which generates p--values and covariates independent of the latter under the null to illustrate how DDHW works:

```{r}
wasserman_normal_sim <- function(m, pi0, xi_min, xi_max, seed=NULL){
    if (!is.null(seed)) set.seed(seed)
    X   <- runif(m, min=xi_min, max=xi_max)
    H   <- rbinom(m,1,1-pi0)
    Z   <- rnorm(m, H*X)
    pvalue <- 1-pnorm(Z)
    simDf <- data.frame(pvalue=pvalue, filterstat=X,H=H, Z=Z)
}

sim <- wasserman_normal_sim(100000, 0.97, 0, 3, seed=1)

```

Now apply DDHW, plot weights and compare number of rejections to number of rejections of the BH method.

```{r}
res_symphony <- ddhw_auto(sim$pvalue,sim$filterstat, 0.1, solver="Rsymphony", nbins=10,  optim_pval_threshold=0.1)
plot(weights(res_symphony))
rejections(res_symphony)
sum(p.adjust(sim$pvalue, method="BH") <= .1)

```

