# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Rcpp_classicTautString_TV1 <- function(input, lambda) {
    .Call(`_IHW_Rcpp_classicTautString_TV1`, input, lambda)
}

#' @export
Grenander_cdf_export <- function(grenander_list, t) {
    .Call(`_IHW_Grenander_cdf_export`, grenander_list, t)
}

#' @export
Grenander_pdf_export <- function(grenander_list, t) {
    .Call(`_IHW_Grenander_pdf_export`, grenander_list, t)
}

#' @export
Grenander_invert_subgradient <- function(grenander_list, lambda) {
    .Call(`_IHW_Grenander_invert_subgradient`, grenander_list, lambda)
}

single_t_FDR <- function(train_grenander, test_ms, alpha) {
    .Call(`_IHW_single_t_FDR`, train_grenander, test_ms, alpha)
}

GrenMix_pdf <- function(train_grenander, test_ms, t) {
    .Call(`_IHW_GrenMix_pdf`, train_grenander, test_ms, t)
}

GrenMix_cdf <- function(train_grenander, test_ms, t) {
    .Call(`_IHW_GrenMix_cdf`, train_grenander, test_ms, t)
}

GrenMix_lagrange_balance <- function(train_grenander, test_ms, lambda, alpha, linearized) {
    .Call(`_IHW_GrenMix_lagrange_balance`, train_grenander, test_ms, lambda, alpha, linearized)
}

unregularized_thresholds_bh <- function(train_grenander, test_ms, alpha) {
    .Call(`_IHW_unregularized_thresholds_bh`, train_grenander, test_ms, alpha)
}

InvertSubgradientTilted <- function(grenander, mu, rho, b, alpha) {
    .Call(`_IHW_InvertSubgradientTilted`, grenander, mu, rho, b, alpha)
}

lambdaMax <- function(train_grenander, test_ms, alpha, mu_dual, single_t) {
    .Call(`_IHW_lambdaMax`, train_grenander, test_ms, alpha, mu_dual, single_t)
}

optimal_ts <- function(train_grenander, test_ms, alpha, lambda_multipliers) {
    .Call(`_IHW_optimal_ts`, train_grenander, test_ms, alpha, lambda_multipliers)
}

start_profiler <- function(str) {
    .Call(`_IHW_start_profiler`, str)
}

stop_profiler <- function() {
    .Call(`_IHW_stop_profiler`)
}

